### ISSUE TITLE
How to set the language to german?

### ISSUE THREAD

**Issue by kllmanu** [hananils/kirby-date-methods#2]
I've tried to set `locale` to `de` and `de_DE.utf-8` in my `config.php`. But it has no effect, I still get all relative dates in english? Does this extension require to set `languages` to `true`?

**Comment by nilshoerrmann** [comment]
Most methods provided by this plugin use PHP's native `DateTime` class under the hood which handles dates in English only. That's why `$field->toDateTime()->format('F')` will always return the month in English – e. g. "January" – and not in the locale set on your server.

For localized dates, please take a look at the [`toFormatted()`](https://github.com/hananils/kirby-date-methods#toformatteddatetype-timetype-timezone-calendar-pattern) and [`toFormattedPattern()`](https://github.com/hananils/kirby-date-methods#toformattedpatternpattern) methods which use PHP's `IntlDateFormatter` under the hood and return dates in the current locale. The `IntlDateFormatter` class knows standard formats for all languages and returns localized dates in different predefined lengths (full, long, medium and short).

`toFormatted()` uses your current locale and returns a long date by default, e. g. `17. Januar 2022`. You can change the format length or add the time by passing additional parameters (see docs). If you need a custom localized date and time format, `toFormattedPattern()` is the right choice. Please note that `IntlDateFormatter` requires other format patterns than the `DateTime` class: https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table.

**Comment by kllmanu** [comment]
I wanted to use `toRelative` and it looks like this plugin even comes with german translations, according to https://github.com/hananils/kirby-date-methods/blob/main/index.php#L30 but it doesn't make use of my locale set. Is there a reason not to do so? Why include those translations then at all?

**Comment by nilshoerrmann** [comment]
You were totally right that this was only working on multilingual sites so far. I've added automatic locale handling to `toRelative()`: on multilingual sites, the locale is set based on the current language as before; for single language sites, you can [set the `locale` in the config](https://getkirby.com/docs/reference/system/options/locale). This conforms to the locale handling of the other methods.

If you need a specific locale different to these setting, there is now an third additional parameter on `dateRelative()`.

**Comment by kllmanu** [comment]
Awesome, thanks a lot! Great plugin!
